In [ ]:
from pathlib import Path
import pandas as pd
import urllib.request
from fiweps.data import d_urls
import numpy as npy

In [ ]:
PROJPATH = Path().resolve().parent

datestr = '202503'

predictordir  = PROJPATH / "data/predictors"
fiwepsdir = Path("/Volumes/CWSCISSD/DataProjects/Ongoing/preseason_predictors/incoming/teleconnections")

### Make seaice dataframe

In [ ]:
areas = ['Bering', 'Chukchi']   # not much change in Beaufort Sea ice
pattern = 'NCEI_seaice_area_monthly'
fpths = [predictordir / f"{pattern}_{area}_{datestr}.csv" for area in areas]
seaicedata = {name: pd.read_csv(fp, skiprows=3,) for (name, fp) in zip(areas, fpths)}
for area in seaicedata:
    seaicedata[area].columns = ['YrMnth', f'{area}_value', f'{area}_anomaly']
    seaicedata[area].set_index('YrMnth', inplace=True)

Let's just get Feb seaice anomalies

In [ ]:
seaice = pd.concat(seaicedata.values(), axis=1)
seaice.reset_index(inplace=True)
seaice['Year'] = seaice['YrMnth'].astype(str).str[:4].astype(int)
seaice['Month'] = seaice['YrMnth'].astype(str).str[4:].astype(int)
seaice = seaice[seaice['Month'].isin([2])]
seaice['label'] = seaice.apply(
    lambda row: 'F' if row.Month in [1, 2] else 'M',
    axis=1
    )
seaice.drop(columns=['YrMnth'], inplace=True)
seaice.drop(columns=['Month'], inplace=True)
seaice.groupby(['Year', 'label']).mean()
seaice

     Bering_value  Bering_anomaly  Chukchi_value  Chukchi_anomaly  Year label
3            0.46           -0.14           0.82            -0.01  1979     F
15           0.70            0.10           0.82            -0.01  1980     F
27           0.64            0.04           0.82            -0.01  1981     F
39           0.48           -0.12           0.82            -0.01  1982     F
51           0.67            0.07           0.82            -0.01  1983     F
63           0.71            0.11           0.82            -0.01  1984     F
75           0.39           -0.21           0.83             0.00  1985     F
87           0.55           -0.05           0.83             0.00  1986     F
99           0.61            0.01           0.83             0.00  1987     F
111          0.56           -0.04           0.83             0.00  1988     F
123          0.42           -0.18           0.82            -0.01  1989     F
135          0.73            0.13           0.83             0.00  1990     F
147          0.79            0.19           0.83             0.00  1991     F
159          0.64            0.04           0.83             0.00  1992     F
171          0.60            0.00           0.83             0.00  1993     F
183          0.50           -0.10           0.82            -0.01  1994     F
195          0.78            0.18           0.83             0.00  1995     F
207          0.52           -0.08           0.83             0.00  1996     F
219          0.63            0.03           0.83             0.00  1997     F
231          0.83            0.23           0.83             0.00  1998     F
243          0.71            0.11           0.83             0.00  1999     F
255          0.65            0.05           0.83             0.00  2000     F
267          0.37           -0.23           0.83             0.00  2001     F
279          0.80            0.20           0.83             0.00  2002     F
291          0.54           -0.06           0.83             0.00  2003     F
303          0.56           -0.04           0.82            -0.01  2004     F
315          0.52           -0.08           0.83             0.00  2005     F
327          0.63            0.03           0.83             0.00  2006     F
339          0.49           -0.11           0.82            -0.01  2007     F
351          0.74            0.14           0.83             0.00  2008     F
363          0.75            0.15           0.83             0.00  2009     F
375          0.74            0.14           0.82            -0.01  2010     F
387          0.59           -0.01           0.82            -0.01  2011     F
399          0.83            0.23           0.83             0.00  2012     F
411          0.79            0.19           0.83             0.00  2013     F
423          0.49           -0.11           0.82            -0.01  2014     F
435          0.46           -0.14           0.82            -0.01  2015     F
447          0.50           -0.10           0.82            -0.01  2016     F
459          0.44           -0.16           0.83             0.00  2017     F
471          0.21           -0.39           0.81            -0.02  2018     F
483          0.29           -0.31           0.82            -0.01  2019     F
495          0.61            0.01           0.83             0.00  2020     F
507          0.50           -0.10           0.83             0.00  2021     F
519          0.67            0.07           0.83             0.00  2022     F
531          0.55           -0.05           0.83             0.00  2023     F
543          0.54           -0.06           0.83             0.00  2024     F
555          0.39           -0.21           0.83             0.00  2025     F

In [ ]:
seaice = seaice[['Year', 'Bering_anomaly']]
seaice.columns = ['Year', 'Bering_anomaly_F']
seaice.set_index('Year', inplace=True)
seaice

      Bering_anomaly_F
Year
1979             -0.14
1980              0.10
1981              0.04
1982             -0.12
1983              0.07
1984              0.11
1985             -0.21
1986             -0.05
1987              0.01
1988             -0.04
1989             -0.18
1990              0.13
1991              0.19
1992              0.04
1993              0.00
1994             -0.10
1995              0.18
1996             -0.08
1997              0.03
1998              0.23
1999              0.11
2000              0.05
2001             -0.23
2002              0.20
2003             -0.06
2004             -0.04
2005             -0.08
2006              0.03
2007             -0.11
2008              0.14
2009              0.15
2010              0.14
2011             -0.01
2012              0.23
2013              0.19
2014             -0.11
2015             -0.14
2016             -0.10
2017             -0.16
2018             -0.39
2019             -0.31
2020              0.01
2021             -0.10
2022              0.07
2023             -0.05
2024             -0.06
2025             -0.21

### Load teleconnections

#### Retrieve teleconnections to share directory

In [ ]:
outdir = fiwepsdir

In [ ]:
d_urls.TELECONNECTIONURLS

[{'name': 'Arctic_Oscillation',
  'shortname': 'AO',
  'format': 'PSL',
  'nodata': -999,
  'skipfooter': 3,
  'URL': 'https://psl.noaa.gov/data/correlation/ao.data'},
 {'name': 'EastPac_NorthPac',
  'shortname': 'EP-NP',
  'skipfooter': 3,
  'format': 'PSL',
  'nodata': -99.9,
  'URL': 'https://psl.noaa.gov/data/correlation/epo.data'},
 {'name': 'Pacific_NA',
  'shortname': 'PNA',
  'format': 'PSL',
  'nodata': -99.9,
  'skipfooter': 3,
  'URL': 'https://psl.noaa.gov/data/correlation/pna.data'},
 {'name': 'Southern_Osc',
  'shortname': 'SOI',
  'format': 'PSL',
  'nodata': -99.99,
  'skipfooter': 3,
  'URL': 'https://psl.noaa.gov/data/correlation/soi.data'},
 {'name': 'Nino1_2',
  'shortname': 'Nino1+2',
  'format': 'PSL',
  'nodata': -99.99,
  'skipfooter': 3,
  'URL': 'https://psl.noaa.gov/data/correlation/nina1.anom.data'},
 {'name': 'Nino3',
  'shortname': 'Nino3',
  'format': 'PSL',
  'nodata': -99.99,
  'skipfooter': 3,
  'URL': 'https://psl.noaa.gov/data/correlation/nina3.anom.data'},
 {'name': 'Nino34',
  'shortname': 'Nino3.4',
  'format': 'PSL',
  'nodata': -99.99,
  'skipfooter': 3,
  'URL': 'https://psl.noaa.gov/data/correlation/nina34.anom.data'},
 {'name': 'Nino4',
  'shortname': 'Nino4',
  'format': 'PSL',
  'nodata': -99.99,
  'skipfooter': 3,
  'URL': 'https://psl.noaa.gov/data/correlation/nina4.anom.data'},
 {'name': 'Pacific_Decadal',
  'shortname': 'PDO',
  'format': 'special',
  'skipfooter': None,
  'nodata': 99.99,
  'URL': 'https://www.ncei.noaa.gov/pub/data/cmb/ersst/v5/index/ersst.v5.pdo.dat'},
 {'name': 'Oceanic_Nino',
  'shortname': 'ONI',
  'format': 'PSL',
  'skipfooter': 8,
  'nodata': -99.9,
  'URL': 'https://psl.noaa.gov/data/correlation/oni.data'},
 {'name': 'North_Pac_Pattern',
  'shortname': 'NPI',
  'format': 'YrMnth',
  'skipfooter': None,
  'URL': 'https://climatedataguide.ucar.edu/sites/default/files/2024-04/npindex_monthly.txt'},
 {'name': 'cpc_multiple_teleconn',
  'shortname': None,
  'format': 'Yr Mnth multiple',
  'skipheader': 17,
  'skipfooter': None,
  'nodata': -99.9,
  'URL': 'https://ftp.cpc.ncep.noaa.gov/wd52dg/data/indices/tele_index.nh'}]

In [ ]:
for item in d_urls.TELECONNECTIONURLS:
    url = item['URL']
    fn = f"{item['name']}.txt"
    print(f"retrieving {fn} from {url}")
    urllib.request.urlretrieve(url, outdir / fn)

retrieving Arctic_Oscillation.txt from https://psl.noaa.gov/data/correlation/ao.data
retrieving EastPac_NorthPac.txt from https://psl.noaa.gov/data/correlation/epo.data
retrieving Pacific_NA.txt from https://psl.noaa.gov/data/correlation/pna.data
retrieving Southern_Osc.txt from https://psl.noaa.gov/data/correlation/soi.data
retrieving Nino1_2.txt from https://psl.noaa.gov/data/correlation/nina1.anom.data
retrieving Nino3.txt from https://psl.noaa.gov/data/correlation/nina3.anom.data
retrieving Nino34.txt from https://psl.noaa.gov/data/correlation/nina34.anom.data
retrieving Nino4.txt from https://psl.noaa.gov/data/correlation/nina4.anom.data
retrieving Pacific_Decadal.txt from https://www.ncei.noaa.gov/pub/data/cmb/ersst/v5/index/ersst.v5.pdo.dat
retrieving Oceanic_Nino.txt from https://psl.noaa.gov/data/correlation/oni.data
retrieving North_Pac_Pattern.txt from https://climatedataguide.ucar.edu/sites/default/files/2024-04/npindex_monthly.txt
retrieving cpc_multiple_teleconn.txt from https://ftp.cpc.ncep.noaa.gov/wd52dg/data/indices/tele_index.nh

In [ ]:
squaredata = ['Arctic_Oscillation.txt', 'Nino3.txt', 
              'EastPac_NorthPac.txt', 'Nino34.txt', 'Southern_Osc.txt',
              'Nino1_2.txt', 'Nino4.txt', 'PacificNA.txt']
extra = 'cpc_multiple_teleconn.txt'
oni = 'Oceanic_Nino.txt'
pdo = 'Pacific_Decadal.txt'
np = 'North_Pac_Pattern.txt'

columns = ['Year'] + [str(ii) for ii in range(1, 13)]

#### Load square teleconnections

In [ ]:
squareteleconn = [teleconn for teleconn in d_urls.TELECONNECTIONURLS if teleconn['format'] == 'PSL']
squareDF = pd.DataFrame.from_records(squareteleconn)
squareDF

,name,shortname,format,nodata,skipfooter,URL
0,Arctic_Oscillation,AO,PSL,-999.00,3,https://psl.noaa.gov/data/correlation/ao.data
1,EastPac_NorthPac,EP-NP,PSL,-99.90,3,https://psl.noaa.gov/data/correlation/epo.data
2,Pacific_NA,PNA,PSL,-99.90,3,https://psl.noaa.gov/data/correlation/pna.data
3,Southern_Osc,SOI,PSL,-99.99,3,https://psl.noaa.gov/data/correlation/soi.data
4,Nino1_2,Nino1+2,PSL,-99.99,3,https://psl.noaa.gov/data/correlation/nina1.an...
5,Nino3,Nino3,PSL,-99.99,3,https://psl.noaa.gov/data/correlation/nina3.an...
6,Nino34,Nino3.4,PSL,-99.99,3,https://psl.noaa.gov/data/correlation/nina34.a...
7,Nino4,Nino4,PSL,-99.99,3,https://psl.noaa.gov/data/correlation/nina4.an...
8,Oceanic_Nino,ONI,PSL,-99.90,8,https://psl.noaa.gov/data/correlation/oni.data

In [ ]:
def get_data(row):
    fp = fiwepsdir / f"{row['name']}.txt"
    data = pd.read_csv(fp, skiprows=1, skipfooter=row.skipfooter, delim_whitespace=True, names=columns,
                       engine='python')
    data = data.astype(float)
    data['Year'] = data['Year'].astype(int)
    data.replace(row.nodata, npy.nan, inplace=True)
    data = data[data['Year'] >= 1979]
    data.meta = row['shortname']
    return data

In [ ]:
results = squareDF.apply(get_data, axis=1)
print(results[0].meta)
results[0]

AO

/var/folders/39/6h0p929579n8vrp25cjkbz3h0000gn/T/ipykernel_41152/262859376.py:3: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  data = pd.read_csv(fp, skiprows=1, skipfooter=row.skipfooter, delim_whitespace=True, names=columns,
/var/folders/39/6h0p929579n8vrp25cjkbz3h0000gn/T/ipykernel_41152/262859376.py:3: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  data = pd.read_csv(fp, skiprows=1, skipfooter=row.skipfooter, delim_whitespace=True, names=columns,
/var/folders/39/6h0p929579n8vrp25cjkbz3h0000gn/T/ipykernel_41152/262859376.py:3: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  data = pd.read_csv(fp, skiprows=1, skipfooter=row.skipfooter, delim_whitespace=True, names=columns,
/var/folders/39/6h0p929579n8vrp25cjkbz3h0000gn/T/ipykernel_41152/262859376.py:3: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  data = pd.read_csv(fp, skiprows=1, skipfooter=row.skipfooter, delim_whitespace=True, names=columns,
/var/folders/39/6h0p929579n8vrp25cjkbz3h0000gn/T/ipykernel_41152/262859376.py:3: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  data = pd.read_csv(fp, skiprows=1, skipfooter=row.skipfooter, delim_whitespace=True, names=columns,
/var/folders/39/6h0p929579n8vrp25cjkbz3h0000gn/T/ipykernel_41152/262859376.py:3: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  data = pd.read_csv(fp, skiprows=1, skipfooter=row.skipfooter, delim_whitespace=True, names=columns,
/var/folders/39/6h0p929579n8vrp25cjkbz3h0000gn/T/ipykernel_41152/262859376.py:3: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  data = pd.read_csv(fp, skiprows=1, skipfooter=row.skipfooter, delim_whitespace=True, names=columns,
/var/folders/39/6h0p929579n8vrp25cjkbz3h0000gn/T/ipykernel_41152/262859376.py:3: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  data = pd.read_csv(fp, skiprows=1, skipfooter=row.skipfooter, delim_whitespace=True, names=columns,
/var/folders/39/6h0p929579n8vrp25cjkbz3h0000gn/T/ipykernel_41152/262859376.py:3: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  data = pd.read_csv(fp, skiprows=1, skipfooter=row.skipfooter, delim_whitespace=True, names=columns,

,Year,1,2,3,4,5,6,7,8,9,10,11,12
29,1979,-2.233,-0.697,-0.814,-1.157,-0.250,0.933,0.038,-0.684,-0.046,-1.243,0.475,1.295
30,1980,-2.066,-0.934,-1.433,-0.419,-1.155,0.722,-0.622,-0.185,0.313,-0.521,-1.361,-0.057
31,1981,-0.116,-0.332,-1.645,0.430,0.180,-0.438,0.560,-0.244,-1.040,-1.167,-0.188,-1.216
32,1982,-0.883,0.974,1.074,1.454,-0.209,-1.180,0.005,0.362,0.558,-0.211,0.661,0.967
33,1983,1.359,-1.806,-0.567,-0.738,-0.441,0.312,0.131,1.098,0.167,1.369,-0.688,0.186
34,1984,0.905,-0.303,-2.386,-0.284,0.479,0.007,0.019,0.466,-0.413,-0.270,-0.966,0.446
35,1985,-2.806,-1.440,0.551,0.652,-0.432,-0.347,-0.390,-0.001,0.114,1.035,-1.218,-1.948
36,1986,-0.568,-2.904,1.931,0.103,0.367,0.535,-0.008,-0.826,-0.023,1.425,0.926,0.060
37,1987,-1.148,-1.473,-1.747,0.387,0.325,-0.710,-0.466,-0.836,0.286,-0.080,-0.536,-0.534
38,1988,0.265,-1.066,-0.197,-0.561,-0.846,0.060,-0.143,0.255,1.039,0.032,-0.035,1.679
39,1989,3.106,3.279,1.530,-0.250,0.889,0.345,0.866,0.551,0.703,0.991,0.034,-0.644
40,1990,1.001,3.402,2.990,1.879,0.943,0.304,-0.296,-0.180,-0.210,0.660,0.521,1.277
41,1991,0.723,-0.876,-0.527,0.530,0.486,-0.115,-0.188,0.797,-0.112,-0.252,0.285,1.613
42,1992,0.550,1.122,0.984,-0.520,1.341,-0.302,0.191,0.535,-0.640,-0.366,0.717,1.627
43,1993,3.495,0.184,0.764,-0.435,-1.607,-0.519,-0.511,-0.393,-0.361,-0.565,1.002,-0.104
44,1994,-0.288,-0.862,1.881,0.225,-0.115,1.606,0.351,0.828,-0.084,0.174,1.779,0.894
45,1995,-0.154,1.429,0.393,-0.963,-0.891,-0.112,-0.217,0.544,-0.549,0.075,-0.723,-2.127
46,1996,-1.200,0.163,-1.483,-1.525,-0.226,0.497,0.715,0.125,-1.140,0.182,0.136,-1.721
47,1997,-0.457,1.889,1.091,0.324,-0.961,-0.815,-0.431,0.121,0.195,-0.700,-0.661,-0.071
48,1998,-2.081,-0.183,-0.254,-0.038,0.429,-0.711,-0.212,0.650,-1.050,0.294,-1.449,1.353
49,1999,0.110,0.482,-1.492,0.284,0.226,0.707,-0.002,-0.672,0.059,-0.006,0.611,1.043
50,2000,1.270,1.076,-0.451,-0.279,0.969,0.586,-0.649,0.144,0.395,0.317,-1.582,-2.354
51,2001,-0.959,-0.622,-1.687,0.906,0.452,-0.015,-0.031,0.520,-0.707,0.708,0.819,-1.322
52,2002,1.381,1.304,0.902,0.748,0.401,0.573,0.328,-0.229,-0.043,-1.488,-1.425,-1.592
53,2003,-0.472,0.128,0.933,-0.178,1.017,-0.102,0.075,-0.280,0.467,-0.670,0.642,0.265
54,2004,-1.686,-1.528,0.318,-0.409,-0.094,-0.236,-0.201,-0.720,0.855,-0.515,0.678,1.230
55,2005,0.356,-1.271,-1.348,-0.046,-0.763,-0.383,-0.030,0.026,0.802,0.030,0.228,-2.104
56,2006,-0.171,-0.156,-1.604,0.138,0.156,1.071,0.103,-0.265,0.607,-1.029,0.521,2.282
57,2007,2.034,-1.307,1.182,0.544,0.894,-0.555,-0.397,-0.034,0.179,0.384,-0.519,0.821
58,2008,0.819,0.938,0.586,-0.455,-1.205,-0.090,-0.480,-0.081,-0.327,1.676,0.092,0.648
59,2009,0.800,-0.672,0.121,0.973,1.194,-1.351,-1.356,-0.054,0.875,-1.540,0.459,-3.413
60,2010,-2.587,-4.266,-0.432,-0.275,-0.919,-0.013,0.435,-0.117,-0.865,-0.467,-0.376,-2.631
61,2011,-1.683,1.575,1.424,2.275,-0.035,-0.858,-0.472,-1.063,0.665,0.800,1.459,2.221
62,2012,-0.220,-0.036,1.037,-0.035,0.168,-0.672,0.168,0.014,0.772,-1.514,-0.111,-1.749
63,2013,-0.610,-1.007,-3.185,0.322,0.494,0.549,-0.011,0.154,-0.461,0.263,2.029,1.475
64,2014,-0.969,0.044,1.206,0.972,0.464,-0.507,-0.489,-0.371,0.102,-1.134,-0.530,0.413
65,2015,1.092,1.043,1.837,1.216,0.763,0.427,-1.108,-0.689,-0.165,-0.250,1.945,1.444
66,2016,-1.449,-0.024,0.280,-1.051,-0.036,0.313,0.085,0.472,0.781,-1.917,-0.611,1.786
67,2017,0.942,0.340,1.365,-0.089,-0.730,0.402,0.634,0.150,-0.492,0.690,-0.078,-0.059
68,2018,-0.281,0.113,-0.941,0.544,1.180,0.380,0.612,0.836,0.585,0.413,-1.116,0.110
69,2019,-0.713,1.149,2.116,-0.255,-1.231,-0.601,-0.890,-0.722,0.306,-0.082,-1.193,0.412
70,2020,2.419,3.417,2.641,0.928,-0.027,-0.122,-0.412,-0.381,0.631,-0.072,2.086,-1.736
71,2021,-2.484,-1.191,2.109,-0.204,-0.161,0.845,0.630,-0.209,-0.252,-0.146,0.093,0.198
72,2022,0.848,1.544,0.305,-0.603,1.224,-0.074,0.025,-0.170,-0.655,1.346,0.339,-2.719
73,2023,-0.674,1.600,0.280,-0.973,1.134,-0.286,-0.154,-0.602,0.318,-0.414,-0.036,-0.222
74,2024,-0.210,0.635,-0.610,0.465,-0.048,0.136,0.587,1.284,-0.624,0.525,-0.037,-0.336
75,2025,-0.069,-0.865,0.556,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
final_results = []
for result in results:
    meta = result.meta
    result.loc[:, '12'] = result['12'].shift(1)
    result = result[result['Year'] >= 1980]
    result[f'{meta}_DJ'] = result[['12', '1']].mean(axis=1)
    result[f'{meta}_FM'] = result[['2', '3']].mean(axis=1)
    result.drop(columns=[str(ii) for ii in range(1, 13)], inplace=True)
    result.set_index('Year', inplace=True)
    final_results.append(result)
    

result_final = pd.concat(final_results, axis=1,)
result_final

/var/folders/39/6h0p929579n8vrp25cjkbz3h0000gn/T/ipykernel_41152/3026687421.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result[f'{meta}_DJ'] = result[['12', '1']].mean(axis=1)
/var/folders/39/6h0p929579n8vrp25cjkbz3h0000gn/T/ipykernel_41152/3026687421.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result[f'{meta}_FM'] = result[['2', '3']].mean(axis=1)
/var/folders/39/6h0p929579n8vrp25cjkbz3h0000gn/T/ipykernel_41152/3026687421.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result.drop(columns=[str(ii) for ii in range(1, 13)], inplace=True)
/var/folders/39/6h0p929579n8vrp25cjkbz3h0000gn/T/ipykernel_41152/3026687421.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result[f'{meta}_DJ'] = result[['12', '1']].mean(axis=1)
/var/folders/39/6h0p929579n8vrp25cjkbz3h0000gn/T/ipykernel_41152/3026687421.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result[f'{meta}_FM'] = result[['2', '3']].mean(axis=1)
/var/folders/39/6h0p929579n8vrp25cjkbz3h0000gn/T/ipykernel_41152/3026687421.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result.drop(columns=[str(ii) for ii in range(1, 13)], inplace=True)
/var/folders/39/6h0p929579n8vrp25cjkbz3h0000gn/T/ipykernel_41152/3026687421.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result[f'{meta}_DJ'] = result[['12', '1']].mean(axis=1)
/var/folders/39/6h0p929579n8vrp25cjkbz3h0000gn/T/ipykernel_41152/3026687421.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result[f'{meta}_FM'] = result[['2', '3']].mean(axis=1)
/var/folders/39/6h0p929579n8vrp25cjkbz3h0000gn/T/ipykernel_41152/3026687421.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result.drop(columns=[str(ii) for ii in range(1, 13)], inplace=True)
/var/folders/39/6h0p929579n8vrp25cjkbz3h0000gn/T/ipykernel_41152/3026687421.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result[f'{meta}_DJ'] = result[['12', '1']].mean(axis=1)
/var/folders/39/6h0p929579n8vrp25cjkbz3h0000gn/T/ipykernel_41152/3026687421.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result[f'{meta}_FM'] = result[['2', '3']].mean(axis=1)
/var/folders/39/6h0p929579n8vrp25cjkbz3h0000gn/T/ipykernel_41152/3026687421.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result.drop(columns=[str(ii) for ii in range(1, 13)], inplace=True)
/var/folders/39/6h0p929579n8vrp25cjkbz3h0000gn/T/ipykernel_41152/3026687421.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result[f'{meta}_DJ'] = result[['12', '1']].mean(axis=1)
/var/folders/39/6h0p929579n8vrp25cjkbz3h0000gn/T/ipykernel_41152/3026687421.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result[f'{meta}_FM'] = result[['2', '3']].mean(axis=1)
/var/folders/39/6h0p929579n8vrp25cjkbz3h0000gn/T/ipykernel_41152/3026687421.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result.drop(columns=[str(ii) for ii in range(1, 13)], inplace=True)
/var/folders/39/6h0p929579n8vrp25cjkbz3h0000gn/T/ipykernel_41152/3026687421.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result[f'{meta}_DJ'] = result[['12', '1']].mean(axis=1)
/var/folders/39/6h0p929579n8vrp25cjkbz3h0000gn/T/ipykernel_41152/3026687421.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result[f'{meta}_FM'] = result[['2', '3']].mean(axis=1)
/var/folders/39/6h0p929579n8vrp25cjkbz3h0000gn/T/ipykernel_41152/3026687421.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result.drop(columns=[str(ii) for ii in range(1, 13)], inplace=True)
/var/folders/39/6h0p929579n8vrp25cjkbz3h0000gn/T/ipykernel_41152/3026687421.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result[f'{meta}_DJ'] = result[['12', '1']].mean(axis=1)
/var/folders/39/6h0p929579n8vrp25cjkbz3h0000gn/T/ipykernel_41152/3026687421.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result[f'{meta}_FM'] = result[['2', '3']].mean(axis=1)
/var/folders/39/6h0p929579n8vrp25cjkbz3h0000gn/T/ipykernel_41152/3026687421.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result.drop(columns=[str(ii) for ii in range(1, 13)], inplace=True)
/var/folders/39/6h0p929579n8vrp25cjkbz3h0000gn/T/ipykernel_41152/3026687421.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result[f'{meta}_DJ'] = result[['12', '1']].mean(axis=1)
/var/folders/39/6h0p929579n8vrp25cjkbz3h0000gn/T/ipykernel_41152/3026687421.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result[f'{meta}_FM'] = result[['2', '3']].mean(axis=1)
/var/folders/39/6h0p929579n8vrp25cjkbz3h0000gn/T/ipykernel_41152/3026687421.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result.drop(columns=[str(ii) for ii in range(1, 13)], inplace=True)
/var/folders/39/6h0p929579n8vrp25cjkbz3h0000gn/T/ipykernel_41152/3026687421.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result[f'{meta}_DJ'] = result[['12', '1']].mean(axis=1)
/var/folders/39/6h0p929579n8vrp25cjkbz3h0000gn/T/ipykernel_41152/3026687421.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result[f'{meta}_FM'] = result[['2', '3']].mean(axis=1)
/var/folders/39/6h0p929579n8vrp25cjkbz3h0000gn/T/ipykernel_41152/3026687421.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result.drop(columns=[str(ii) for ii in range(1, 13)], inplace=True)

,AO_DJ,AO_FM,EP-NP_DJ,EP-NP_FM,PNA_DJ,PNA_FM,SOI_DJ,SOI_FM,Nino1+2_DJ,Nino1+2_FM,Nino3_DJ,Nino3_FM,Nino3.4_DJ,Nino3.4_FM,Nino4_DJ,Nino4_FM,ONI_DJ,ONI_FM
Year,,,,,,,,,,,,,,,,,,
1980,-0.3855,-1.1835,0.53,0.505,-0.845,0.695,-0.25,-0.10,-0.165,-0.215,0.405,-0.075,0.530,0.125,0.330,0.275,0.615,0.400
1981,-0.0865,-0.9885,1.02,0.000,0.945,0.740,0.25,-1.20,-0.950,-0.860,-0.350,-0.735,-0.155,-0.640,-0.080,-0.170,-0.135,-0.485
1982,-1.0495,1.0240,1.11,0.785,-1.085,-1.430,1.40,0.70,-0.220,-1.040,0.075,-0.050,-0.035,-0.020,-0.060,-0.055,-0.065,0.130
1983,1.1630,-1.1865,-0.31,-0.455,0.660,1.735,-4.75,-5.00,2.905,2.130,2.930,1.990,2.275,1.660,0.450,0.280,2.205,1.730
1984,0.5455,-1.3445,-0.97,-0.215,-0.005,0.905,0.15,0.50,-0.090,-0.875,-0.710,-0.190,-0.850,-0.355,-0.830,-0.785,-0.755,-0.380
1985,-1.1800,-0.4445,1.00,-1.540,-0.230,-1.090,-0.35,1.65,-0.590,-1.135,-1.265,-0.840,-1.250,-0.755,-0.795,-0.860,-1.090,-0.810
1986,-1.2580,-0.4865,0.52,0.450,0.840,0.460,1.00,-0.45,-0.190,-0.415,-0.765,-0.450,-0.535,-0.565,-0.245,-0.195,-0.425,-0.390
1987,-0.5440,-1.6100,-0.74,0.120,0.845,0.710,-1.75,-2.10,0.795,1.205,0.970,1.070,1.130,1.055,0.310,0.485,1.225,1.125
1988,-0.1345,-0.6315,1.13,0.065,0.265,0.875,-0.50,0.25,0.345,-0.560,0.840,-0.080,0.920,0.190,0.705,0.295,0.960,0.340
1989,2.3925,2.4045,-1.81,1.470,-0.620,-1.635,2.25,1.90,-0.525,-0.105,-1.525,-0.985,-1.965,-1.340,-1.745,-1.345,-1.770,-1.255
1990,0.1785,3.1960,-0.58,-0.915,-0.260,-1.370,-0.50,-1.85,-0.440,-0.300,-0.335,-0.135,-0.060,0.125,0.020,0.345,0.045,0.245
1991,1.0000,-0.7015,-0.45,-0.035,-0.710,-0.040,0.30,-0.35,-0.520,-0.295,0.025,-0.080,0.420,0.175,0.615,0.440,0.410,0.240
1992,1.0815,1.0530,-0.17,0.990,0.580,0.275,-3.80,-2.40,0.650,0.925,1.310,1.160,1.765,1.580,0.715,0.765,1.620,1.555
1993,2.5610,0.4740,-0.65,1.165,-1.505,0.690,-1.20,-1.00,-0.055,0.450,-0.235,0.395,-0.005,0.400,0.145,0.075,-0.020,0.400
1994,-0.1960,0.5095,2.38,-0.295,-0.190,-0.520,0.05,-0.35,-0.035,-0.670,0.145,-0.215,0.130,0.085,0.145,-0.005,0.060,0.120
1995,0.3700,0.9110,1.03,0.330,0.295,0.355,-1.35,0.50,0.795,-0.195,0.795,0.210,1.135,0.595,0.820,0.710,1.025,0.625
1996,-1.6635,-0.6600,0.26,1.340,-0.030,-0.725,0.40,1.15,-0.750,-0.385,-0.895,-0.600,-0.905,-0.735,-0.485,-0.460,-0.940,-0.670
1997,-1.0890,1.4900,0.22,-0.045,-0.685,-0.555,1.15,1.10,-1.015,0.160,-0.950,-0.515,-0.585,-0.310,-0.090,0.215,-0.495,-0.230
1998,-1.0760,-0.2185,0.62,0.490,0.575,0.790,-3.00,-3.70,3.900,2.690,3.190,2.205,2.335,1.685,0.605,0.445,2.315,1.685
1999,0.7315,-0.5050,-0.89,-0.925,-0.415,-0.040,2.65,1.85,-0.480,-0.290,-1.175,-0.700,-1.690,-1.135,-1.580,-1.495,-1.560,-1.185
2000,1.1565,0.3125,-0.92,-0.475,-0.895,1.075,1.75,2.45,-0.700,-0.545,-1.605,-0.820,-1.755,-1.265,-1.345,-1.450,-1.655,-1.240
2001,-1.6565,-1.1545,-0.90,-0.450,1.105,-0.060,1.45,2.15,-0.795,-0.155,-0.540,-0.145,-0.825,-0.555,-0.920,-0.765,-0.710,-0.480
2002,0.0295,1.1030,-0.11,0.550,-0.220,-0.835,-0.35,0.70,-0.900,0.350,-0.555,-0.050,-0.280,-0.015,0.260,0.355,-0.230,0.060
2003,-1.0320,0.5305,2.07,0.750,1.145,0.160,-1.05,-0.80,0.615,-0.095,0.890,0.315,0.985,0.500,0.705,0.645,1.030,0.505
2004,-0.7105,-0.6050,0.66,-0.890,0.220,0.560,-0.20,1.35,0.005,-0.405,0.595,0.215,0.350,0.175,0.430,0.240,0.360,0.270
2005,0.7930,-1.3095,0.73,0.010,-0.330,0.225,-0.35,-2.35,0.170,-1.200,0.505,-0.080,0.700,0.405,0.875,0.640,0.665,0.515
2006,-1.1375,-0.8800,-1.07,0.385,0.485,-0.500,1.35,1.55,-0.645,-0.035,-1.015,-0.450,-0.915,-0.690,-0.380,-0.630,-0.845,-0.670
2007,2.1580,-0.0625,-1.14,-0.170,0.910,-0.270,-0.90,0.10,0.685,-0.265,1.005,-0.160,0.920,-0.025,0.785,0.400,0.800,0.050
2008,0.8200,0.7620,-1.25,-1.010,-0.610,-0.120,2.80,3.40,-1.070,0.305,-1.560,-0.995,-1.630,-1.440,-1.285,-1.465,-1.620,-1.405
2009,0.7240,-0.2755,-0.18,-0.400,-0.790,-1.430,2.10,1.90,-0.310,-0.745,-0.535,-0.640,-0.875,-0.740,-0.880,-0.715,-0.790,-0.700
2010,-3.0000,-2.3490,-0.58,-1.070,0.500,1.080,-1.50,-1.75,0.440,0.095,1.200,0.715,1.630,1.075,1.150,0.815,1.530,1.030
2011,-2.1570,1.4995,-0.42,-0.075,-0.540,-1.015,4.30,4.35,-0.690,-0.520,-1.380,-0.750,-1.570,-1.020,-1.425,-0.930,-1.505,-1.060
2012,1.0005,0.5005,-1.92,-1.460,0.095,0.255,2.95,1.00,-0.430,0.260,-0.745,-0.185,-0.965,-0.640,-1.015,-0.840,-0.950,-0.655
2013,-1.1795,-2.0960,0.12,-0.090,-0.630,0.020,-0.55,1.05,-0.765,-0.700,-0.540,-0.340,-0.390,-0.385,-0.010,-0.280,-0.320,-0.385
2014,0.2530,0.6250,1.11,0.775,-0.285,-1.035,1.25,-0.70,-0.225,-0.460,-0.280,-0.555,-0.330,-0.450,-0.120,0.175,-0.345,-0.365
2015,0.7525,1.4400,1.27,1.155,0.255,-0.015,-1.15,-0.40,0.125,-0.220,0.515,0.075,0.610,0.445,0.755,0.885,0.605,0.500
2016,-0.0025,0.1280,-0.35,0.235,1.205,1.045,-2.25,-1.65,2.000,1.325,2.715,1.750,2.615,1.940,1.295,1.145,2.560,1.860
2017,1.3640,0.8525,0.39,-0.415,-0.470,-0.040,0.40,0.70,0.680,1.485,-0.275,0.385,-0.465,-0.025,-0.175,-0.060,-0.450,-0.055
2018,-0.1700,-0.4140,0.66,0.265,0.220,-1.415,0.80,0.80,-1.270,-1.160,-1.200,-0.915,-0.980,-0.790,-0.480,-0.285,-0.945,-0.775
2019,-0.3015,1.6325,1.07,1.655,0.490,-0.890,0.80,-1.40,0.940,0.320,0.760,0.615,0.770,0.760,0.835,0.675,0.780,0.715
2020,1.4155,3.0290,-0.60,-0.675,-0.535,-1.240,-0.30,-0.15,-0.205,-0.020,0.230,0.150,0.560,0.425,0.860,0.765,0.525,0.440
2021,-2.1100,0.4590,-0.71,-1.045,0.435,-0.975,3.10,1.55,-0.740,-0.805,-0.720,-0.710,-1.075,-0.900,-1.025,-0.805,-1.120,-0.885
2022,0.5230,0.9245,0.51,-0.275,-1.100,0.210,1.65,2.35,-1.400,-1.170,-1.290,-0.935,-1.000,-0.930,-0.555,-0.530,-0.975,-0.960
2023,-1.6965,0.9400,1.36,-0.040,-0.665,-1.520,2.90,1.30,-0.510,0.985,-0.690,0.100,-0.785,-0.285,-0.750,-0.400,-0.755,-0.290
2024,-0.2160,0.0125,0.08,-0.020,0.415,-0.015,0.20,-0.85,1.450,0.685,1.935,1.175,1.920,1.325,1.520,1.125,1.865,1.310
2025,-0.2025,-0.1545,-0.35,0.625,1.045,0.600,1.10,1.85,-0.175,0.840,-0.340,0.240,-0.670,-0.220,-0.425,-0.470,-0.555,-0.390

#### Load PDO

In [ ]:
fp_pdo = fiwepsdir / f"{pdo}"
data_pdo = pd.read_csv(fp_pdo, skiprows=2, sep='\s+', names=columns,
                       engine='python')
data_pdo = data_pdo.astype(float)
data_pdo['Year'] = data_pdo['Year'].astype(int)
data_pdo.replace(99.99, npy.nan, inplace=True)
data_pdo.loc[:, '12'] = data_pdo['12'].shift(1)
data_pdo = data_pdo[data_pdo['Year'] >= 1980]
data_pdo.meta = 'PDO'
data_pdo[f'{data_pdo.meta}_DJ'] = data_pdo[['12', '1']].mean(axis=1)
data_pdo[f'{data_pdo.meta}_FM'] = data_pdo[['2', '3']].mean(axis=1)
data_pdo.drop(columns=[str(ii) for ii in range(1, 13)], inplace=True)
data_pdo.set_index('Year', inplace=True)


data_pdo

      PDO_DJ  PDO_FM
Year
1980   0.060   0.600
1981   0.740   1.230
1982   0.350  -0.280
1983   0.280   1.350
1984   1.570   1.395
1985   0.675   0.070
1986   0.685   1.575
1987   1.590   1.405
1988   0.585   0.480
1989  -0.690  -1.345
1990  -0.260  -1.260
1991  -2.010  -1.100
1992  -0.065   0.145
1993   0.025   0.130
1994   0.760   0.300
1995  -1.540   0.240
1996   0.725   0.930
1997   0.205   0.340
1998   1.020   1.405
1999  -0.935  -1.120
2000  -2.060  -0.970
2001   0.240  -0.210
2002  -0.770  -1.390
2003   1.510   1.120
2004  -0.575  -0.180
2005  -0.395   0.345
2006   0.220  -0.180
2007  -0.555  -0.905
2008  -1.185  -1.360
2009  -1.560  -1.920
2010  -0.230   0.045
2011  -1.920  -1.370
2012  -2.125  -1.505
2013  -1.205  -1.450
2014  -0.805  -0.060
2015   1.685   1.425
2016   0.520   1.425
2017   0.275   0.040
2018   0.175  -0.405
2019  -0.275  -0.560
2020  -0.705  -1.615
2021  -0.800  -1.380
2022  -2.555  -1.790
2023  -1.725  -2.050
2024  -1.615  -1.425
2025  -1.655  -1.265

#### Load rest of teleconnections from CPC

In [ ]:
fp_extra = fiwepsdir / f"{extra}"
with open(fp_extra, 'r') as src:
    txt = src.read().replace('-', ' -')
with open(fp_extra, 'w') as dst:
    dst.write(txt)

In [ ]:
def helper(row):
    if row.Month == 12:
        row['Year'] += 1
    return row

In [ ]:
columns = ['Year', 'Month', 'NAO', 'EA', 'WP', 'EP/NP', 'PNA', 'EA-WR', 'SCA', 'TNH', 'POL', 'PT', 'P2']
data_extra = pd.read_csv(fp_extra, skiprows=19, delim_whitespace=True, names=columns, engine='python')


data_extra = data_extra.astype(float)
data_extra['Year'] = data_extra['Year'].astype(int)
data_extra.replace(-99.9, npy.nan, inplace=True)

data_extra.apply(helper, axis=1)
data_extra = data_extra[data_extra['Year'] >= 1980]
data_extra = data_extra[data_extra['Month'].isin([1, 2, 3, 12])]
data_extra['label'] = data_extra.apply(
    lambda row: 'FM' if row.Month in [2, 3] else 'DJ',
    axis=1
    )
data_extra.drop(columns=['Month', 'EP/NP', 'PNA', 'TNH', 'PT', 'P2'], inplace=True)
data_extra = data_extra.groupby(['Year', 'label']).mean().reset_index().pivot(
    index='Year', columns='label', values=['NAO', 'EA', 'WP', 'EA-WR', 'SCA', 'POL'])
data_extra.columns = data_extra.columns.to_series().apply('_'.join)

data_extra

/var/folders/39/6h0p929579n8vrp25cjkbz3h0000gn/T/ipykernel_41152/1567164845.py:2: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  data_extra = pd.read_csv(fp_extra, skiprows=19, delim_whitespace=True, names=columns, engine='python')

,NAO_DJ,NAO_FM,EA_DJ,EA_FM,WP_DJ,WP_FM,EA-WR_DJ,EA-WR_FM,SCA_DJ,SCA_FM,POL_DJ,POL_FM
Year,,,,,,,,,,,,
1980,-0.375,-0.560,-1.185,0.025,-2.060,0.295,-0.430,-0.860,-0.535,1.045,-0.675,0.235
1981,-0.095,-0.525,-0.970,0.315,-0.040,0.025,-0.755,-0.115,-0.610,-0.140,0.990,-0.330
1982,0.005,0.830,-0.785,-0.275,0.725,-0.365,0.160,1.035,-0.525,0.725,-0.035,-0.145
1983,0.760,-0.225,0.270,-0.705,-0.425,-1.015,0.165,0.220,-1.600,-0.025,-1.035,0.030
1984,0.665,-0.210,-0.745,-0.620,-0.535,-0.685,-1.000,-1.960,1.190,1.385,-0.150,0.740
1985,-1.135,-0.595,-0.330,-0.350,-0.785,0.345,-0.195,0.280,0.235,0.435,-1.405,-0.120
1986,0.805,-0.095,0.175,-0.130,-0.265,-1.565,0.155,0.640,0.325,1.045,-0.020,1.535
1987,-0.820,-0.765,0.505,-0.375,1.660,0.295,1.020,0.225,-0.600,0.255,-0.545,0.205
1988,0.580,-0.080,-0.095,-0.215,0.580,0.415,-0.170,-1.835,-0.630,0.545,0.730,-0.090
1989,-0.150,1.680,1.060,-0.200,-0.360,-0.725,0.605,-0.255,-0.945,-0.880,0.165,0.790
1990,0.405,1.145,-0.295,1.430,0.990,0.055,-0.225,-0.085,0.005,-1.825,-0.645,0.070
1991,0.415,0.065,-0.190,0.425,-0.505,0.525,1.460,-0.185,0.005,1.320,0.550,0.175
1992,-0.155,0.640,-0.295,-0.135,0.215,0.155,1.425,0.110,-0.100,0.190,1.035,0.640
1993,1.355,0.210,0.530,-0.925,0.335,-0.120,-0.155,1.130,-0.665,-0.020,0.540,1.685
1994,1.240,0.500,0.485,0.765,0.370,-0.690,0.070,-0.315,0.555,0.265,0.440,-0.150
1995,-0.535,0.880,0.330,-0.715,-0.950,-1.545,-0.210,-0.020,-0.490,-1.200,0.695,-0.165
1996,-1.025,-0.590,-1.025,-0.885,-0.160,-0.115,-0.645,-1.260,1.335,0.965,-0.180,1.635
1997,-1.030,1.305,0.805,0.665,-0.700,-0.200,0.970,0.030,0.340,-1.100,1.840,-0.850
1998,0.335,-0.030,0.405,0.910,0.330,0.855,-0.060,0.805,-0.180,-0.305,-1.120,0.335
1999,0.895,-0.135,0.095,-1.825,-0.520,1.350,-0.910,0.410,-0.175,-0.015,-0.030,-0.620
2000,-0.220,0.940,-0.170,-0.135,-0.445,-0.200,-0.060,-0.515,-0.040,-1.040,-0.675,-1.535
2001,-0.540,-0.830,0.320,0.420,0.035,0.260,-0.195,-0.115,1.065,-0.300,0.025,-0.915
2002,-0.480,0.560,1.150,1.030,0.250,0.800,1.150,-0.085,0.130,-1.000,-0.075,-0.350
2003,0.090,0.095,0.310,0.435,0.330,-0.420,-0.040,1.055,-0.725,0.595,0.955,1.050
2004,0.090,0.035,-0.820,0.765,-0.690,0.365,-0.055,0.750,-0.060,0.490,-0.105,-1.165
2005,0.380,-1.415,-1.495,-0.505,-1.485,0.060,-0.315,-0.125,0.290,0.025,-0.575,0.145
2006,1.060,-1.385,-0.015,-0.635,0.945,1.275,1.065,0.455,1.035,-0.270,-0.660,-0.180
2007,-0.010,0.065,0.695,0.945,1.090,-0.455,0.140,0.360,-0.950,0.535,-0.170,-0.610
2008,0.090,0.030,-0.895,0.315,0.965,-0.670,-1.050,-0.175,0.420,-0.985,-0.415,0.095
2009,-1.200,-0.095,1.030,-1.030,-0.530,0.965,-1.075,-0.495,0.460,0.010,-0.420,-0.395
2010,-1.800,-2.010,-0.055,1.240,-0.395,1.030,-1.270,0.030,0.915,0.320,0.325,-1.520
2011,0.360,0.295,-0.600,-0.180,-0.880,-0.115,-0.440,0.330,0.145,-0.340,0.165,0.535
2012,0.465,0.480,-0.540,-1.185,-1.080,0.915,-0.670,0.355,1.285,-0.065,-0.995,-0.615
2013,0.340,-1.525,1.040,-0.050,-0.970,1.040,0.050,0.515,-0.325,0.215,-1.345,-0.780
2014,0.730,0.755,0.390,1.575,0.205,-0.900,-0.880,-1.020,0.675,0.315,-0.860,-0.910
2015,1.780,1.085,2.125,0.580,0.170,-0.480,0.520,-0.325,-0.050,0.010,0.275,1.385
2016,-0.010,0.860,0.940,1.280,0.965,0.705,0.510,-1.065,-0.930,-0.385,-1.865,-1.280
2017,0.390,0.530,-0.825,0.805,0.440,-1.140,-0.500,0.060,-0.155,-0.175,-0.495,0.175
2018,0.825,-0.020,0.995,-1.000,0.270,0.620,-1.025,1.315,0.895,-0.190,0.030,-1.085
2019,0.600,0.390,-0.430,0.410,0.895,1.485,0.435,-0.350,0.375,-0.665,-0.175,0.810
2020,0.340,0.820,0.470,0.635,0.840,1.375,-0.225,0.255,0.890,-1.785,0.125,0.680
2021,-0.810,0.035,-0.050,0.520,1.465,1.405,-0.690,1.905,0.315,-0.310,-1.050,-1.300
2022,0.260,0.930,-0.715,0.835,-0.730,0.095,-0.020,0.245,-0.010,-0.555,-0.775,-1.075
2023,1.325,-0.485,0.255,-0.160,1.600,1.575,-0.265,1.765,0.705,-1.390,-0.795,-0.015
2024,0.380,0.080,1.250,1.625,0.170,1.265,0.280,0.435,-0.920,0.135,-0.760,-0.800
2025,-1.120,0.635,2.700,0.730,1.020,0.545,-1.340,0.205,-0.720,0.600,0.210,-1.460

#### Concatenate full teleconnections dataframe

In [ ]:
teleconnections = pd.concat([result_final, data_pdo, data_extra], axis=1,)
teleconnections

,AO_DJ,AO_FM,EP-NP_DJ,EP-NP_FM,PNA_DJ,PNA_FM,SOI_DJ,SOI_FM,Nino1+2_DJ,Nino1+2_FM,...,EA_DJ,EA_FM,WP_DJ,WP_FM,EA-WR_DJ,EA-WR_FM,SCA_DJ,SCA_FM,POL_DJ,POL_FM
Year,,,,,,,,,,,,,,,,,,,,,
1980,-0.3855,-1.1835,0.53,0.505,-0.845,0.695,-0.25,-0.10,-0.165,-0.215,...,-1.185,0.025,-2.060,0.295,-0.430,-0.860,-0.535,1.045,-0.675,0.235
1981,-0.0865,-0.9885,1.02,0.000,0.945,0.740,0.25,-1.20,-0.950,-0.860,...,-0.970,0.315,-0.040,0.025,-0.755,-0.115,-0.610,-0.140,0.990,-0.330
1982,-1.0495,1.0240,1.11,0.785,-1.085,-1.430,1.40,0.70,-0.220,-1.040,...,-0.785,-0.275,0.725,-0.365,0.160,1.035,-0.525,0.725,-0.035,-0.145
1983,1.1630,-1.1865,-0.31,-0.455,0.660,1.735,-4.75,-5.00,2.905,2.130,...,0.270,-0.705,-0.425,-1.015,0.165,0.220,-1.600,-0.025,-1.035,0.030
1984,0.5455,-1.3445,-0.97,-0.215,-0.005,0.905,0.15,0.50,-0.090,-0.875,...,-0.745,-0.620,-0.535,-0.685,-1.000,-1.960,1.190,1.385,-0.150,0.740
1985,-1.1800,-0.4445,1.00,-1.540,-0.230,-1.090,-0.35,1.65,-0.590,-1.135,...,-0.330,-0.350,-0.785,0.345,-0.195,0.280,0.235,0.435,-1.405,-0.120
1986,-1.2580,-0.4865,0.52,0.450,0.840,0.460,1.00,-0.45,-0.190,-0.415,...,0.175,-0.130,-0.265,-1.565,0.155,0.640,0.325,1.045,-0.020,1.535
1987,-0.5440,-1.6100,-0.74,0.120,0.845,0.710,-1.75,-2.10,0.795,1.205,...,0.505,-0.375,1.660,0.295,1.020,0.225,-0.600,0.255,-0.545,0.205
1988,-0.1345,-0.6315,1.13,0.065,0.265,0.875,-0.50,0.25,0.345,-0.560,...,-0.095,-0.215,0.580,0.415,-0.170,-1.835,-0.630,0.545,0.730,-0.090
1989,2.3925,2.4045,-1.81,1.470,-0.620,-1.635,2.25,1.90,-0.525,-0.105,...,1.060,-0.200,-0.360,-0.725,0.605,-0.255,-0.945,-0.880,0.165,0.790
1990,0.1785,3.1960,-0.58,-0.915,-0.260,-1.370,-0.50,-1.85,-0.440,-0.300,...,-0.295,1.430,0.990,0.055,-0.225,-0.085,0.005,-1.825,-0.645,0.070
1991,1.0000,-0.7015,-0.45,-0.035,-0.710,-0.040,0.30,-0.35,-0.520,-0.295,...,-0.190,0.425,-0.505,0.525,1.460,-0.185,0.005,1.320,0.550,0.175
1992,1.0815,1.0530,-0.17,0.990,0.580,0.275,-3.80,-2.40,0.650,0.925,...,-0.295,-0.135,0.215,0.155,1.425,0.110,-0.100,0.190,1.035,0.640
1993,2.5610,0.4740,-0.65,1.165,-1.505,0.690,-1.20,-1.00,-0.055,0.450,...,0.530,-0.925,0.335,-0.120,-0.155,1.130,-0.665,-0.020,0.540,1.685
1994,-0.1960,0.5095,2.38,-0.295,-0.190,-0.520,0.05,-0.35,-0.035,-0.670,...,0.485,0.765,0.370,-0.690,0.070,-0.315,0.555,0.265,0.440,-0.150
1995,0.3700,0.9110,1.03,0.330,0.295,0.355,-1.35,0.50,0.795,-0.195,...,0.330,-0.715,-0.950,-1.545,-0.210,-0.020,-0.490,-1.200,0.695,-0.165
1996,-1.6635,-0.6600,0.26,1.340,-0.030,-0.725,0.40,1.15,-0.750,-0.385,...,-1.025,-0.885,-0.160,-0.115,-0.645,-1.260,1.335,0.965,-0.180,1.635
1997,-1.0890,1.4900,0.22,-0.045,-0.685,-0.555,1.15,1.10,-1.015,0.160,...,0.805,0.665,-0.700,-0.200,0.970,0.030,0.340,-1.100,1.840,-0.850
1998,-1.0760,-0.2185,0.62,0.490,0.575,0.790,-3.00,-3.70,3.900,2.690,...,0.405,0.910,0.330,0.855,-0.060,0.805,-0.180,-0.305,-1.120,0.335
1999,0.7315,-0.5050,-0.89,-0.925,-0.415,-0.040,2.65,1.85,-0.480,-0.290,...,0.095,-1.825,-0.520,1.350,-0.910,0.410,-0.175,-0.015,-0.030,-0.620
2000,1.1565,0.3125,-0.92,-0.475,-0.895,1.075,1.75,2.45,-0.700,-0.545,...,-0.170,-0.135,-0.445,-0.200,-0.060,-0.515,-0.040,-1.040,-0.675,-1.535
2001,-1.6565,-1.1545,-0.90,-0.450,1.105,-0.060,1.45,2.15,-0.795,-0.155,...,0.320,0.420,0.035,0.260,-0.195,-0.115,1.065,-0.300,0.025,-0.915
2002,0.0295,1.1030,-0.11,0.550,-0.220,-0.835,-0.35,0.70,-0.900,0.350,...,1.150,1.030,0.250,0.800,1.150,-0.085,0.130,-1.000,-0.075,-0.350
2003,-1.0320,0.5305,2.07,0.750,1.145,0.160,-1.05,-0.80,0.615,-0.095,...,0.310,0.435,0.330,-0.420,-0.040,1.055,-0.725,0.595,0.955,1.050
2004,-0.7105,-0.6050,0.66,-0.890,0.220,0.560,-0.20,1.35,0.005,-0.405,...,-0.820,0.765,-0.690,0.365,-0.055,0.750,-0.060,0.490,-0.105,-1.165
2005,0.7930,-1.3095,0.73,0.010,-0.330,0.225,-0.35,-2.35,0.170,-1.200,...,-1.495,-0.505,-1.485,0.060,-0.315,-0.125,0.290,0.025,-0.575,0.145
2006,-1.1375,-0.8800,-1.07,0.385,0.485,-0.500,1.35,1.55,-0.645,-0.035,...,-0.015,-0.635,0.945,1.275,1.065,0.455,1.035,-0.270,-0.660,-0.180
2007,2.1580,-0.0625,-1.14,-0.170,0.910,-0.270,-0.90,0.10,0.685,-0.265,...,0.695,0.945,1.090,-0.455,0.140,0.360,-0.950,0.535,-0.170,-0.610
2008,0.8200,0.7620,-1.25,-1.010,-0.610,-0.120,2.80,3.40,-1.070,0.305,...,-0.895,0.315,0.965,-0.670,-1.050,-0.175,0.420,-0.985,-0.415,0.095
2009,0.7240,-0.2755,-0.18,-0.400,-0.790,-1.430,2.10,1.90,-0.310,-0.745,...,1.030,-1.030,-0.530,0.965,-1.075,-0.495,0.460,0.010,-0.420,-0.395
2010,-3.0000,-2.3490,-0.58,-1.070,0.500,1.080,-1.50,-1.75,0.440,0.095,...,-0.055,1.240,-0.395,1.030,-1.270,0.030,0.915,0.320,0.325,-1.520
2011,-2.1570,1.4995,-0.42,-0.075,-0.540,-1.015,4.30,4.35,-0.690,-0.520,...,-0.600,-0.180,-0.880,-0.115,-0.440,0.330,0.145,-0.340,0.165,0.535
2012,1.0005,0.5005,-1.92,-1.460,0.095,0.255,2.95,1.00,-0.430,0.260,...,-0.540,-1.185,-1.080,0.915,-0.670,0.355,1.285,-0.065,-0.995,-0.615
2013,-1.1795,-2.0960,0.12,-0.090,-0.630,0.020,-0.55,1.05,-0.765,-0.700,...,1.040,-0.050,-0.970,1.040,0.050,0.515,-0.325,0.215,-1.345,-0.780
2014,0.2530,0.6250,1.11,0.775,-0.285,-1.035,1.25,-0.70,-0.225,-0.460,...,0.390,1.575,0.205,-0.900,-0.880,-1.020,0.675,0.315,-0.860,-0.910
2015,0.7525,1.4400,1.27,1.155,0.255,-0.015,-1.15,-0.40,0.125,-0.220,...,2.125,0.580,0.170,-0.480,0.520,-0.325,-0.050,0.010,0.275,1.385
2016,-0.0025,0.1280,-0.35,0.235,1.205,1.045,-2.25,-1.65,2.000,1.325,...,0.940,1.280,0.965,0.705,0.510,-1.065,-0.930,-0.385,-1.865,-1.280
2017,1.3640,0.8525,0.39,-0.415,-0.470,-0.040,0.40,0.70,0.680,1.485,...,-0.825,0.805,0.440,-1.140,-0.500,0.060,-0.155,-0.175,-0.495,0.175
2018,-0.1700,-0.4140,0.66,0.265,0.220,-1.415,0.80,0.80,-1.270,-1.160,...,0.995,-1.000,0.270,0.620,-1.025,1.315,0.895,-0.190,0.030,-1.085
2019,-0.3015,1.6325,1.07,1.655,0.490,-0.890,0.80,-1.40,0.940,0.320,...,-0.430,0.410,0.895,1.485,0.435,-0.350,0.375,-0.665,-0.175,0.810
2020,1.4155,3.0290,-0.60,-0.675,-0.535,-1.240,-0.30,-0.15,-0.205,-0.020,...,0.470,0.635,0.840,1.375,-0.225,0.255,0.890,-1.785,0.125,0.680
2021,-2.1100,0.4590,-0.71,-1.045,0.435,-0.975,3.10,1.55,-0.740,-0.805,...,-0.050,0.520,1.465,1.405,-0.690,1.905,0.315,-0.310,-1.050,-1.300
2022,0.5230,0.9245,0.51,-0.275,-1.100,0.210,1.65,2.35,-1.400,-1.170,...,-0.715,0.835,-0.730,0.095,-0.020,0.245,-0.010,-0.555,-0.775,-1.075
2023,-1.6965,0.9400,1.36,-0.040,-0.665,-1.520,2.90,1.30,-0.510,0.985,...,0.255,-0.160,1.600,1.575,-0.265,1.765,0.705,-1.390,-0.795,-0.015
2024,-0.2160,0.0125,0.08,-0.020,0.415,-0.015,0.20,-0.85,1.450,0.685,...,1.250,1.625,0.170,1.265,0.280,0.435,-0.920,0.135,-0.760,-0.800
2025,-0.2025,-0.1545,-0.35,0.625,1.045,0.600,1.10,1.85,-0.175,0.840,...,2.700,0.730,1.020,0.545,-1.340,0.205,-0.720,0.600,0.210,-1.460

April 2024: all dj and FM

In [ ]:
outfn = f'teleconnections_{datestr}.csv'
outpath = predictordir 

teleconnections.to_csv(outpath / outfn, float_format='%.3f')

### March temps

In [ ]:
tmpfpth = predictordir / f"Fairbanks_March_tavg_202503.csv"
tempdata = pd.read_csv(tmpfpth, skiprows=3,) 
tempdata.columns = ['YrMnth', 'tavg']
tempdata['Year'] = tempdata['YrMnth'].astype(str).str[:4].astype(int)
tempdata['Month'] = tempdata['YrMnth'].astype(str).str[4:].astype(int)
tempdata = tempdata[tempdata['Month'].isin([3])]
tempdata.columns = ['YrMnth', 'tavg_M', 'Year','Month']
tempdata.drop(columns=['YrMnth'], inplace=True)
tempdata.drop(columns=['Month'], inplace=True)
tempdata
# for area in seaicedata:
#     seaicedata[area].columns = ['YrMnth', f'{area}_value', f'{area}_anomaly']
#     seaicedata[area].set_index('YrMnth', inplace=True)

    YrMnth  tavg_M  Year  Month
0   195303    19.1  1953      3
1   195403    22.4  1954      3
2   195503    23.1  1955      3
3   195603    19.5  1956      3
4   195703    28.7  1957      3
..     ...     ...   ...    ...
67  202003    21.6  2020      3
68  202103    19.3  2021      3
69  202203    32.4  2022      3
70  202303    25.1  2023      3
71  202403    28.9  2024      3

[72 rows x 4 columns]

### Ice thickness

In [ ]:
icedata = predictordir / 'ice_thickness_POR_BobBusey.csv'
ice = pd.read_csv(icedata).set_index('year')
ice.columns = ['icethick_Nenana']
ice_average = ice.icethick_Nenana.mean()
ice_extras = { key: ice_average for key in range(1980, 1989)}
ice_extrasDF = pd.DataFrame.from_dict(ice_extras, orient='index')
ice_extrasDF.index.name = 'Year'
ice_extrasDF.columns = ['icethick_Nenana']
ice = pd.concat([ice_extrasDF, ice])

In [ ]:
ice

      icethick_Nenana
1980        39.545946
1981        39.545946
1982        39.545946
1983        39.545946
1984        39.545946
1985        39.545946
1986        39.545946
1987        39.545946
1988        39.545946
1989        42.000000
1990        36.000000
1991        38.000000
1992        47.000000
1993        26.000000
1994        51.000000
1995        34.000000
1996        45.000000
1997        42.500000
1998        38.000000
1999        46.000000
2000        37.700000
2001        38.800000
2002        48.000000
2003        48.200000
2004        35.500000
2005        32.000000
2006        32.700000
2007        48.800000
2008        45.600000
2009        46.000000
2010        46.300000
2011        41.100000
2012        44.300000
2013        49.300000
2014        40.200000
2015        33.300000
2016        36.000000
2017        39.150000
2018        26.700000
2019        25.300000
2020        34.500000
2021        45.200000
2022        31.250000
2023        30.800000
2024        49.000000
2025        32.000000

In [ ]:
### Save out sea ice + teleconnections dataframe

In [ ]:
predictors = pd.concat([teleconnections, seaice, ice], axis=1,).dropna()
predictors

,AO_DJ,AO_FM,EP-NP_DJ,EP-NP_FM,PNA_DJ,PNA_FM,SOI_DJ,SOI_FM,Nino1+2_DJ,Nino1+2_FM,...,WP_DJ,WP_FM,EA-WR_DJ,EA-WR_FM,SCA_DJ,SCA_FM,POL_DJ,POL_FM,Bering_anomaly_F,icethick_Nenana
1980,-0.3855,-1.1835,0.53,0.505,-0.845,0.695,-0.25,-0.10,-0.165,-0.215,...,-2.060,0.295,-0.430,-0.860,-0.535,1.045,-0.675,0.235,0.10,39.545946
1981,-0.0865,-0.9885,1.02,0.000,0.945,0.740,0.25,-1.20,-0.950,-0.860,...,-0.040,0.025,-0.755,-0.115,-0.610,-0.140,0.990,-0.330,0.04,39.545946
1982,-1.0495,1.0240,1.11,0.785,-1.085,-1.430,1.40,0.70,-0.220,-1.040,...,0.725,-0.365,0.160,1.035,-0.525,0.725,-0.035,-0.145,-0.12,39.545946
1983,1.1630,-1.1865,-0.31,-0.455,0.660,1.735,-4.75,-5.00,2.905,2.130,...,-0.425,-1.015,0.165,0.220,-1.600,-0.025,-1.035,0.030,0.07,39.545946
1984,0.5455,-1.3445,-0.97,-0.215,-0.005,0.905,0.15,0.50,-0.090,-0.875,...,-0.535,-0.685,-1.000,-1.960,1.190,1.385,-0.150,0.740,0.11,39.545946
1985,-1.1800,-0.4445,1.00,-1.540,-0.230,-1.090,-0.35,1.65,-0.590,-1.135,...,-0.785,0.345,-0.195,0.280,0.235,0.435,-1.405,-0.120,-0.21,39.545946
1986,-1.2580,-0.4865,0.52,0.450,0.840,0.460,1.00,-0.45,-0.190,-0.415,...,-0.265,-1.565,0.155,0.640,0.325,1.045,-0.020,1.535,-0.05,39.545946
1987,-0.5440,-1.6100,-0.74,0.120,0.845,0.710,-1.75,-2.10,0.795,1.205,...,1.660,0.295,1.020,0.225,-0.600,0.255,-0.545,0.205,0.01,39.545946
1988,-0.1345,-0.6315,1.13,0.065,0.265,0.875,-0.50,0.25,0.345,-0.560,...,0.580,0.415,-0.170,-1.835,-0.630,0.545,0.730,-0.090,-0.04,39.545946
1989,2.3925,2.4045,-1.81,1.470,-0.620,-1.635,2.25,1.90,-0.525,-0.105,...,-0.360,-0.725,0.605,-0.255,-0.945,-0.880,0.165,0.790,-0.18,42.000000
1990,0.1785,3.1960,-0.58,-0.915,-0.260,-1.370,-0.50,-1.85,-0.440,-0.300,...,0.990,0.055,-0.225,-0.085,0.005,-1.825,-0.645,0.070,0.13,36.000000
1991,1.0000,-0.7015,-0.45,-0.035,-0.710,-0.040,0.30,-0.35,-0.520,-0.295,...,-0.505,0.525,1.460,-0.185,0.005,1.320,0.550,0.175,0.19,38.000000
1992,1.0815,1.0530,-0.17,0.990,0.580,0.275,-3.80,-2.40,0.650,0.925,...,0.215,0.155,1.425,0.110,-0.100,0.190,1.035,0.640,0.04,47.000000
1993,2.5610,0.4740,-0.65,1.165,-1.505,0.690,-1.20,-1.00,-0.055,0.450,...,0.335,-0.120,-0.155,1.130,-0.665,-0.020,0.540,1.685,0.00,26.000000
1994,-0.1960,0.5095,2.38,-0.295,-0.190,-0.520,0.05,-0.35,-0.035,-0.670,...,0.370,-0.690,0.070,-0.315,0.555,0.265,0.440,-0.150,-0.10,51.000000
1995,0.3700,0.9110,1.03,0.330,0.295,0.355,-1.35,0.50,0.795,-0.195,...,-0.950,-1.545,-0.210,-0.020,-0.490,-1.200,0.695,-0.165,0.18,34.000000
1996,-1.6635,-0.6600,0.26,1.340,-0.030,-0.725,0.40,1.15,-0.750,-0.385,...,-0.160,-0.115,-0.645,-1.260,1.335,0.965,-0.180,1.635,-0.08,45.000000
1997,-1.0890,1.4900,0.22,-0.045,-0.685,-0.555,1.15,1.10,-1.015,0.160,...,-0.700,-0.200,0.970,0.030,0.340,-1.100,1.840,-0.850,0.03,42.500000
1998,-1.0760,-0.2185,0.62,0.490,0.575,0.790,-3.00,-3.70,3.900,2.690,...,0.330,0.855,-0.060,0.805,-0.180,-0.305,-1.120,0.335,0.23,38.000000
1999,0.7315,-0.5050,-0.89,-0.925,-0.415,-0.040,2.65,1.85,-0.480,-0.290,...,-0.520,1.350,-0.910,0.410,-0.175,-0.015,-0.030,-0.620,0.11,46.000000
2000,1.1565,0.3125,-0.92,-0.475,-0.895,1.075,1.75,2.45,-0.700,-0.545,...,-0.445,-0.200,-0.060,-0.515,-0.040,-1.040,-0.675,-1.535,0.05,37.700000
2001,-1.6565,-1.1545,-0.90,-0.450,1.105,-0.060,1.45,2.15,-0.795,-0.155,...,0.035,0.260,-0.195,-0.115,1.065,-0.300,0.025,-0.915,-0.23,38.800000
2002,0.0295,1.1030,-0.11,0.550,-0.220,-0.835,-0.35,0.70,-0.900,0.350,...,0.250,0.800,1.150,-0.085,0.130,-1.000,-0.075,-0.350,0.20,48.000000
2003,-1.0320,0.5305,2.07,0.750,1.145,0.160,-1.05,-0.80,0.615,-0.095,...,0.330,-0.420,-0.040,1.055,-0.725,0.595,0.955,1.050,-0.06,48.200000
2004,-0.7105,-0.6050,0.66,-0.890,0.220,0.560,-0.20,1.35,0.005,-0.405,...,-0.690,0.365,-0.055,0.750,-0.060,0.490,-0.105,-1.165,-0.04,35.500000
2005,0.7930,-1.3095,0.73,0.010,-0.330,0.225,-0.35,-2.35,0.170,-1.200,...,-1.485,0.060,-0.315,-0.125,0.290,0.025,-0.575,0.145,-0.08,32.000000
2006,-1.1375,-0.8800,-1.07,0.385,0.485,-0.500,1.35,1.55,-0.645,-0.035,...,0.945,1.275,1.065,0.455,1.035,-0.270,-0.660,-0.180,0.03,32.700000
2007,2.1580,-0.0625,-1.14,-0.170,0.910,-0.270,-0.90,0.10,0.685,-0.265,...,1.090,-0.455,0.140,0.360,-0.950,0.535,-0.170,-0.610,-0.11,48.800000
2008,0.8200,0.7620,-1.25,-1.010,-0.610,-0.120,2.80,3.40,-1.070,0.305,...,0.965,-0.670,-1.050,-0.175,0.420,-0.985,-0.415,0.095,0.14,45.600000
2009,0.7240,-0.2755,-0.18,-0.400,-0.790,-1.430,2.10,1.90,-0.310,-0.745,...,-0.530,0.965,-1.075,-0.495,0.460,0.010,-0.420,-0.395,0.15,46.000000
2010,-3.0000,-2.3490,-0.58,-1.070,0.500,1.080,-1.50,-1.75,0.440,0.095,...,-0.395,1.030,-1.270,0.030,0.915,0.320,0.325,-1.520,0.14,46.300000
2011,-2.1570,1.4995,-0.42,-0.075,-0.540,-1.015,4.30,4.35,-0.690,-0.520,...,-0.880,-0.115,-0.440,0.330,0.145,-0.340,0.165,0.535,-0.01,41.100000
2012,1.0005,0.5005,-1.92,-1.460,0.095,0.255,2.95,1.00,-0.430,0.260,...,-1.080,0.915,-0.670,0.355,1.285,-0.065,-0.995,-0.615,0.23,44.300000
2013,-1.1795,-2.0960,0.12,-0.090,-0.630,0.020,-0.55,1.05,-0.765,-0.700,...,-0.970,1.040,0.050,0.515,-0.325,0.215,-1.345,-0.780,0.19,49.300000
2014,0.2530,0.6250,1.11,0.775,-0.285,-1.035,1.25,-0.70,-0.225,-0.460,...,0.205,-0.900,-0.880,-1.020,0.675,0.315,-0.860,-0.910,-0.11,40.200000
2015,0.7525,1.4400,1.27,1.155,0.255,-0.015,-1.15,-0.40,0.125,-0.220,...,0.170,-0.480,0.520,-0.325,-0.050,0.010,0.275,1.385,-0.14,33.300000
2016,-0.0025,0.1280,-0.35,0.235,1.205,1.045,-2.25,-1.65,2.000,1.325,...,0.965,0.705,0.510,-1.065,-0.930,-0.385,-1.865,-1.280,-0.10,36.000000
2017,1.3640,0.8525,0.39,-0.415,-0.470,-0.040,0.40,0.70,0.680,1.485,...,0.440,-1.140,-0.500,0.060,-0.155,-0.175,-0.495,0.175,-0.16,39.150000
2018,-0.1700,-0.4140,0.66,0.265,0.220,-1.415,0.80,0.80,-1.270,-1.160,...,0.270,0.620,-1.025,1.315,0.895,-0.190,0.030,-1.085,-0.39,26.700000
2019,-0.3015,1.6325,1.07,1.655,0.490,-0.890,0.80,-1.40,0.940,0.320,...,0.895,1.485,0.435,-0.350,0.375,-0.665,-0.175,0.810,-0.31,25.300000
2020,1.4155,3.0290,-0.60,-0.675,-0.535,-1.240,-0.30,-0.15,-0.205,-0.020,...,0.840,1.375,-0.225,0.255,0.890,-1.785,0.125,0.680,0.01,34.500000
2021,-2.1100,0.4590,-0.71,-1.045,0.435,-0.975,3.10,1.55,-0.740,-0.805,...,1.465,1.405,-0.690,1.905,0.315,-0.310,-1.050,-1.300,-0.10,45.200000
2022,0.5230,0.9245,0.51,-0.275,-1.100,0.210,1.65,2.35,-1.400,-1.170,...,-0.730,0.095,-0.020,0.245,-0.010,-0.555,-0.775,-1.075,0.07,31.250000
2023,-1.6965,0.9400,1.36,-0.040,-0.665,-1.520,2.90,1.30,-0.510,0.985,...,1.600,1.575,-0.265,1.765,0.705,-1.390,-0.795,-0.015,-0.05,30.800000
2024,-0.2160,0.0125,0.08,-0.020,0.415,-0.015,0.20,-0.85,1.450,0.685,...,0.170,1.265,0.280,0.435,-0.920,0.135,-0.760,-0.800,-0.06,49.000000
2025,-0.2025,-0.1545,-0.35,0.625,1.045,0.600,1.10,1.85,-0.175,0.840,...,1.020,0.545,-1.340,0.205,-0.720,0.600,0.210,-1.460,-0.21,32.000000

In [ ]:
outfn = f'predictors_tele_seaice_{datestr}.csv'
outpath = predictordir 

predictors.to_csv(outpath / outfn, float_format='%.3f')

### Now load the breakup data

In [ ]:
location = 'Tanana River at Nenana'

In [ ]:
breakupdata = PROJPATH / "data/breakupdata/derived/breakupDate_cleaned.csv"
breakup = pd.read_csv(breakupdata, skiprows=3, index_col=0)
breakup = breakup[breakup.siteID==location]
breakup = breakup[['year', 'JulianDay']].rename({'year': 'Year'}, axis=1)
breakup.set_index('Year', inplace=True)
breakup

      JulianDay
Year
2024        118
2023        128
2022        122
2021        120
2020        118
2019        104
2018        121
2017        121
2016        114
2015        114
2014        115
2013        140
2012        114
2011        124
2010        119
2009        121
2008        127
2007        117
2006        127
2005        118
2004        115
2003        119
1999        119
2002        127
2001        128
2000        122
1998        110
1997        120
1996        127
1995        116
1994        119
1993        114
1992        135
1991        121
1990        114
1989        121
1988        118
1987        125
1986        128
1985        131
1984        130
1983        119
1982        130
1981        120
1980        120

In [ ]:
fulldf = pd.concat([predictors, breakup], axis=1,)
fulldf

,AO_DJ,AO_FM,EP-NP_DJ,EP-NP_FM,PNA_DJ,PNA_FM,SOI_DJ,SOI_FM,Nino1+2_DJ,Nino1+2_FM,...,WP_FM,EA-WR_DJ,EA-WR_FM,SCA_DJ,SCA_FM,POL_DJ,POL_FM,Bering_anomaly_F,icethick_Nenana,JulianDay
1980,-0.3855,-1.1835,0.53,0.505,-0.845,0.695,-0.25,-0.10,-0.165,-0.215,...,0.295,-0.430,-0.860,-0.535,1.045,-0.675,0.235,0.10,39.545946,120.0
1981,-0.0865,-0.9885,1.02,0.000,0.945,0.740,0.25,-1.20,-0.950,-0.860,...,0.025,-0.755,-0.115,-0.610,-0.140,0.990,-0.330,0.04,39.545946,120.0
1982,-1.0495,1.0240,1.11,0.785,-1.085,-1.430,1.40,0.70,-0.220,-1.040,...,-0.365,0.160,1.035,-0.525,0.725,-0.035,-0.145,-0.12,39.545946,130.0
1983,1.1630,-1.1865,-0.31,-0.455,0.660,1.735,-4.75,-5.00,2.905,2.130,...,-1.015,0.165,0.220,-1.600,-0.025,-1.035,0.030,0.07,39.545946,119.0
1984,0.5455,-1.3445,-0.97,-0.215,-0.005,0.905,0.15,0.50,-0.090,-0.875,...,-0.685,-1.000,-1.960,1.190,1.385,-0.150,0.740,0.11,39.545946,130.0
1985,-1.1800,-0.4445,1.00,-1.540,-0.230,-1.090,-0.35,1.65,-0.590,-1.135,...,0.345,-0.195,0.280,0.235,0.435,-1.405,-0.120,-0.21,39.545946,131.0
1986,-1.2580,-0.4865,0.52,0.450,0.840,0.460,1.00,-0.45,-0.190,-0.415,...,-1.565,0.155,0.640,0.325,1.045,-0.020,1.535,-0.05,39.545946,128.0
1987,-0.5440,-1.6100,-0.74,0.120,0.845,0.710,-1.75,-2.10,0.795,1.205,...,0.295,1.020,0.225,-0.600,0.255,-0.545,0.205,0.01,39.545946,125.0
1988,-0.1345,-0.6315,1.13,0.065,0.265,0.875,-0.50,0.25,0.345,-0.560,...,0.415,-0.170,-1.835,-0.630,0.545,0.730,-0.090,-0.04,39.545946,118.0
1989,2.3925,2.4045,-1.81,1.470,-0.620,-1.635,2.25,1.90,-0.525,-0.105,...,-0.725,0.605,-0.255,-0.945,-0.880,0.165,0.790,-0.18,42.000000,121.0
1990,0.1785,3.1960,-0.58,-0.915,-0.260,-1.370,-0.50,-1.85,-0.440,-0.300,...,0.055,-0.225,-0.085,0.005,-1.825,-0.645,0.070,0.13,36.000000,114.0
1991,1.0000,-0.7015,-0.45,-0.035,-0.710,-0.040,0.30,-0.35,-0.520,-0.295,...,0.525,1.460,-0.185,0.005,1.320,0.550,0.175,0.19,38.000000,121.0
1992,1.0815,1.0530,-0.17,0.990,0.580,0.275,-3.80,-2.40,0.650,0.925,...,0.155,1.425,0.110,-0.100,0.190,1.035,0.640,0.04,47.000000,135.0
1993,2.5610,0.4740,-0.65,1.165,-1.505,0.690,-1.20,-1.00,-0.055,0.450,...,-0.120,-0.155,1.130,-0.665,-0.020,0.540,1.685,0.00,26.000000,114.0
1994,-0.1960,0.5095,2.38,-0.295,-0.190,-0.520,0.05,-0.35,-0.035,-0.670,...,-0.690,0.070,-0.315,0.555,0.265,0.440,-0.150,-0.10,51.000000,119.0
1995,0.3700,0.9110,1.03,0.330,0.295,0.355,-1.35,0.50,0.795,-0.195,...,-1.545,-0.210,-0.020,-0.490,-1.200,0.695,-0.165,0.18,34.000000,116.0
1996,-1.6635,-0.6600,0.26,1.340,-0.030,-0.725,0.40,1.15,-0.750,-0.385,...,-0.115,-0.645,-1.260,1.335,0.965,-0.180,1.635,-0.08,45.000000,127.0
1997,-1.0890,1.4900,0.22,-0.045,-0.685,-0.555,1.15,1.10,-1.015,0.160,...,-0.200,0.970,0.030,0.340,-1.100,1.840,-0.850,0.03,42.500000,120.0
1998,-1.0760,-0.2185,0.62,0.490,0.575,0.790,-3.00,-3.70,3.900,2.690,...,0.855,-0.060,0.805,-0.180,-0.305,-1.120,0.335,0.23,38.000000,110.0
1999,0.7315,-0.5050,-0.89,-0.925,-0.415,-0.040,2.65,1.85,-0.480,-0.290,...,1.350,-0.910,0.410,-0.175,-0.015,-0.030,-0.620,0.11,46.000000,119.0
2000,1.1565,0.3125,-0.92,-0.475,-0.895,1.075,1.75,2.45,-0.700,-0.545,...,-0.200,-0.060,-0.515,-0.040,-1.040,-0.675,-1.535,0.05,37.700000,122.0
2001,-1.6565,-1.1545,-0.90,-0.450,1.105,-0.060,1.45,2.15,-0.795,-0.155,...,0.260,-0.195,-0.115,1.065,-0.300,0.025,-0.915,-0.23,38.800000,128.0
2002,0.0295,1.1030,-0.11,0.550,-0.220,-0.835,-0.35,0.70,-0.900,0.350,...,0.800,1.150,-0.085,0.130,-1.000,-0.075,-0.350,0.20,48.000000,127.0
2003,-1.0320,0.5305,2.07,0.750,1.145,0.160,-1.05,-0.80,0.615,-0.095,...,-0.420,-0.040,1.055,-0.725,0.595,0.955,1.050,-0.06,48.200000,119.0
2004,-0.7105,-0.6050,0.66,-0.890,0.220,0.560,-0.20,1.35,0.005,-0.405,...,0.365,-0.055,0.750,-0.060,0.490,-0.105,-1.165,-0.04,35.500000,115.0
2005,0.7930,-1.3095,0.73,0.010,-0.330,0.225,-0.35,-2.35,0.170,-1.200,...,0.060,-0.315,-0.125,0.290,0.025,-0.575,0.145,-0.08,32.000000,118.0
2006,-1.1375,-0.8800,-1.07,0.385,0.485,-0.500,1.35,1.55,-0.645,-0.035,...,1.275,1.065,0.455,1.035,-0.270,-0.660,-0.180,0.03,32.700000,127.0
2007,2.1580,-0.0625,-1.14,-0.170,0.910,-0.270,-0.90,0.10,0.685,-0.265,...,-0.455,0.140,0.360,-0.950,0.535,-0.170,-0.610,-0.11,48.800000,117.0
2008,0.8200,0.7620,-1.25,-1.010,-0.610,-0.120,2.80,3.40,-1.070,0.305,...,-0.670,-1.050,-0.175,0.420,-0.985,-0.415,0.095,0.14,45.600000,127.0
2009,0.7240,-0.2755,-0.18,-0.400,-0.790,-1.430,2.10,1.90,-0.310,-0.745,...,0.965,-1.075,-0.495,0.460,0.010,-0.420,-0.395,0.15,46.000000,121.0
2010,-3.0000,-2.3490,-0.58,-1.070,0.500,1.080,-1.50,-1.75,0.440,0.095,...,1.030,-1.270,0.030,0.915,0.320,0.325,-1.520,0.14,46.300000,119.0
2011,-2.1570,1.4995,-0.42,-0.075,-0.540,-1.015,4.30,4.35,-0.690,-0.520,...,-0.115,-0.440,0.330,0.145,-0.340,0.165,0.535,-0.01,41.100000,124.0
2012,1.0005,0.5005,-1.92,-1.460,0.095,0.255,2.95,1.00,-0.430,0.260,...,0.915,-0.670,0.355,1.285,-0.065,-0.995,-0.615,0.23,44.300000,114.0
2013,-1.1795,-2.0960,0.12,-0.090,-0.630,0.020,-0.55,1.05,-0.765,-0.700,...,1.040,0.050,0.515,-0.325,0.215,-1.345,-0.780,0.19,49.300000,140.0
2014,0.2530,0.6250,1.11,0.775,-0.285,-1.035,1.25,-0.70,-0.225,-0.460,...,-0.900,-0.880,-1.020,0.675,0.315,-0.860,-0.910,-0.11,40.200000,115.0
2015,0.7525,1.4400,1.27,1.155,0.255,-0.015,-1.15,-0.40,0.125,-0.220,...,-0.480,0.520,-0.325,-0.050,0.010,0.275,1.385,-0.14,33.300000,114.0
2016,-0.0025,0.1280,-0.35,0.235,1.205,1.045,-2.25,-1.65,2.000,1.325,...,0.705,0.510,-1.065,-0.930,-0.385,-1.865,-1.280,-0.10,36.000000,114.0
2017,1.3640,0.8525,0.39,-0.415,-0.470,-0.040,0.40,0.70,0.680,1.485,...,-1.140,-0.500,0.060,-0.155,-0.175,-0.495,0.175,-0.16,39.150000,121.0
2018,-0.1700,-0.4140,0.66,0.265,0.220,-1.415,0.80,0.80,-1.270,-1.160,...,0.620,-1.025,1.315,0.895,-0.190,0.030,-1.085,-0.39,26.700000,121.0
2019,-0.3015,1.6325,1.07,1.655,0.490,-0.890,0.80,-1.40,0.940,0.320,...,1.485,0.435,-0.350,0.375,-0.665,-0.175,0.810,-0.31,25.300000,104.0
2020,1.4155,3.0290,-0.60,-0.675,-0.535,-1.240,-0.30,-0.15,-0.205,-0.020,...,1.375,-0.225,0.255,0.890,-1.785,0.125,0.680,0.01,34.500000,118.0
2021,-2.1100,0.4590,-0.71,-1.045,0.435,-0.975,3.10,1.55,-0.740,-0.805,...,1.405,-0.690,1.905,0.315,-0.310,-1.050,-1.300,-0.10,45.200000,120.0
2022,0.5230,0.9245,0.51,-0.275,-1.100,0.210,1.65,2.35,-1.400,-1.170,...,0.095,-0.020,0.245,-0.010,-0.555,-0.775,-1.075,0.07,31.250000,122.0
2023,-1.6965,0.9400,1.36,-0.040,-0.665,-1.520,2.90,1.30,-0.510,0.985,...,1.575,-0.265,1.765,0.705,-1.390,-0.795,-0.015,-0.05,30.800000,128.0
2024,-0.2160,0.0125,0.08,-0.020,0.415,-0.015,0.20,-0.85,1.450,0.685,...,1.265,0.280,0.435,-0.920,0.135,-0.760,-0.800,-0.06,49.000000,118.0
2025,-0.2025,-0.1545,-0.35,0.625,1.045,0.600,1.10,1.85,-0.175,0.840,...,0.545,-1.340,0.205,-0.720,0.600,0.210,-1.460,-0.21,32.000000,NaN

In [ ]:
outdir  = PROJPATH / "data/ML_2025_Nenana/DF"
outpth = outdir / f"DF_{location.replace(' ', '_')}"
fulldf.to_csv(outpth, float_format='%.3f')